version: '3.7'
services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_USER=root
      - DB_PASSWORD=my25267943y520
      - DB_HOST=107.182.27.36
      - DB_PORT=3306
      - DB_NAME=diary
      - LOGPATH=/app/log
      - SECRET_KEY=dksS7^Q1~)%(;m
    volumes:
      - /root/work/diary_image:/app/files
      - /root/work/log:/app/log
    command: ["gunicorn", "--workers=4", "-b", "0.0.0.0:8888", "app:application"]

  nginx:
    build:
      context: .
      dockerfile: NginxDockerfile
    ports:
      - "80:80"
    volumes:
      - /root/work/diary_image:/images_data
      - ./nginx:/etc/nginx/conf.d
      - ./static:/static_files
    links:
      - webapp
